/* ******************************************************************************
 * 
 *  Mark Sattolo (epistemik@gmail.com)
 * ----------------------------------------------- 
 *  $File: //depot/Eclipse/Java/workspace/MineSwinger/src/mhs/mineswinger/Msgs.java $
 *  $Revision: #2 $
 *  $Change: 147 $
 *  $DateTime: 2011/11/05 09:31:40 $
 * -----------------------------------------------
 * 
 * Messages.java
 * Created on Feb 2, 2008, 22h53
 * Initial git version created Apr 12, 2015
 * 
 ********************************************************************************/

package mhs.mineswinger;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Generated by Eclipse
 * @version $Revision: #2 $
 */
public class Msgs
{
  private static final String BUNDLE_NAME = "mhs.mineswinger.messages" ; //$NON-NLS-1$
  
  private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle( BUNDLE_NAME );
  
  /** CONSTRUCTOR  */
  private Msgs()
  {}
  
  /**
   * Use the supplied key to find a String in the properties file
   * @param key - of String to find
   * @return the requested String
   */
  public static String str( final String key )
  {
    try
    {
      return RESOURCE_BUNDLE.getString( key );
    }
    catch( MissingResourceException e )
    {
      System.err.println( "Missing key " + key ); //$NON-NLS-1$
      return '!' + key + '!';
    }
  }
}
